# Generated by Django 5.2.8 on 2025-11-14 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Комната 305» или «Большой конференц-зал»', max_length=100, verbose_name='Название комнаты')),
                ('description', models.TextField(help_text='Подробное описание комнаты', verbose_name='Описание')),
                ('capacity', models.PositiveIntegerField(help_text='Количество человек, которое может поместиться в комнату', verbose_name='Вместимость')),
                ('has_projector', models.BooleanField(default=False, help_text='Указывает, есть ли проектор в комнате', verbose_name='Наличие проектора')),
                ('has_whiteboard', models.BooleanField(default=False, help_text='Указывает, есть ли доска в комнате', verbose_name='Наличие доски')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало бронирования')),
                ('end_time', models.DateTimeField(verbose_name='Окончание бронирования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['start_time'],
            },
        ),
    ]
