server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Чтобы работало с React Router (если будет)
    # location / {
    #   try_files $uri $uri/ /index.html;
    # }

    # Заголовки для безопасности
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
}
